/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

/**
 *
 * @author Aditya
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JbtnCustomer = new javax.swing.JButton();
        JBtnEmp = new javax.swing.JButton();
        JBtnOrd = new javax.swing.JButton();
        JBtnOrdDet = new javax.swing.JButton();
        JbtnPrd = new javax.swing.JButton();
        JbtnPrdVen = new javax.swing.JButton();
        JbtnVend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JbtnCustomer.setText("Customers");
        JbtnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnCustomerActionPerformed(evt);
            }
        });

        JBtnEmp.setText("Employees");
        JBtnEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnEmpActionPerformed(evt);
            }
        });

        JBtnOrd.setText("Orders");
        JBtnOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnOrdActionPerformed(evt);
            }
        });

        JBtnOrdDet.setText("Order Details");
        JBtnOrdDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnOrdDetActionPerformed(evt);
            }
        });

        JbtnPrd.setText("Products");
        JbtnPrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnPrdActionPerformed(evt);
            }
        });

        JbtnPrdVen.setText("Product Vendors");
        JbtnPrdVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnPrdVenActionPerformed(evt);
            }
        });

        JbtnVend.setText("Vendors");
        JbtnVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnVendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JbtnPrd)
                    .addComponent(JBtnOrd)
                    .addComponent(JbtnCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBtnEmp)
                    .addComponent(JBtnOrdDet)
                    .addComponent(JbtnPrdVen))
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(JbtnVend)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbtnCustomer)
                    .addComponent(JBtnEmp))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtnOrd)
                    .addComponent(JBtnOrdDet))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbtnPrd)
                    .addComponent(JbtnPrdVen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(JbtnVend)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbtnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnCustomerActionPerformed
        // TODO add your handling code here:
       
        Customer cust = new Customer ();
        cust.setVisible(true);
    }//GEN-LAST:event_JbtnCustomerActionPerformed

    private void JBtnEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnEmpActionPerformed
        // TODO add your handling code here:
        Employee emp = new Employee ();
        emp.setVisible (true);
    }//GEN-LAST:event_JBtnEmpActionPerformed

    private void JBtnOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnOrdActionPerformed
        // TODO add your handling code here:
        Orders ord = new Orders ();
        ord.setVisible (true);
    }//GEN-LAST:event_JBtnOrdActionPerformed

    private void JBtnOrdDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnOrdDetActionPerformed
        // TODO add your handling code here:
        OrderDetails orddet = new OrderDetails();
        orddet.setVisible (true);
    }//GEN-LAST:event_JBtnOrdDetActionPerformed

    private void JbtnPrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnPrdActionPerformed
        // TODO add your handling code here:
                Product prd = new Product ();
        prd.setVisible (true);

    }//GEN-LAST:event_JbtnPrdActionPerformed

    private void JbtnPrdVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnPrdVenActionPerformed
        // TODO add your handling code here:
                ProductVendors prdven = new ProductVendors();
        prdven.setVisible (true);

    }//GEN-LAST:event_JbtnPrdVenActionPerformed

    private void JbtnVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnVendActionPerformed
        // TODO add your handling code here:
        Vendors vend = new Vendors ();
        vend.setVisible (true);

    }//GEN-LAST:event_JbtnVendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    /*jBtnEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
*/
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnEmp;
    private javax.swing.JButton JBtnOrd;
    private javax.swing.JButton JBtnOrdDet;
    private javax.swing.JButton JbtnCustomer;
    private javax.swing.JButton JbtnPrd;
    private javax.swing.JButton JbtnPrdVen;
    private javax.swing.JButton JbtnVend;
    // End of variables declaration//GEN-END:variables

    
}
